### ISSUE TITLE
The issue of inconsistent testing results with the 3DCDNet compared to the paper

### ISSUE THREAD

**Issue by ZYJ0409** [wangle53/3DCDNet#1]
Hello! I followed the instructions in the readme file, downloaded the SLPCCD dataset and pre-trained models, modified the dataset path, and placed the pre-trained model in the designated folder. Finally, I tested 3DCDNet on the SLPCCD dataset, but the miou score only reached 0.29, while in your paper the miou score reached 0.74. May I ask where I went wrong?

**Comment by wangle53** [comment]
Did you revised the configs.py?

**Comment by wangle53** [comment]
Thanks for your interest and reminding. We have updated the source codes which have been revised and validated. Please you download the latest files to cover the last version.

**Comment by ZYJ0409** [comment]
Thank you for providing an answer!

**Comment by LinLin1031** [comment]
![image](https://github.com/wangle53/3DCDNet/assets/50825626/e151ae88-2405-4a2b-9a9a-c646eef1c38e)

![image](https://github.com/wangle53/3DCDNet/assets/50825626/30ecb569-8596-440c-a395-e2e24a062905)

I have tested using the pre-trained model you provided and the results are shown in the graph with an mIoU of 72.41. Why doesn't it reach the 74.45 in Figure 2 (from the paper)? @wangle53

**Comment by wangle53** [comment]
The main reason is that the number of points in some samples in the SLPCCD is too small. This results in a large difference in point clouds after multiple sampling. This was also confirmed in our subsequent experiments. So there are two suggestions，first，repea t experiments with different sampling;second, do experiments on dataset Urb3DCD which is more reliable than SLPCCD.
