### ISSUE TITLE
A question about the SLPCCD dataset.

### ISSUE THREAD

**Issue by ZYJ0409** [wangle53/3DCDNet#2]
I would like to ask what the labels 0 and 1 represent in the SLPCCD dataset.

**Comment by wangle53** [comment]
'0' denotes unchanged points, '1' denotes changed points. Points labeled with  '1'in PC-2016 denote the removed points, and points labeled with '1' in PC-2020 denote the added points.

**Comment by ZYJ0409** [comment]
Thank you for your response.

**Comment by LinLin1031** [comment]
https://github.com/wangle53/3DCDNet/blob/4aaf38bbb9f7591ce1e3f32bcab38d21ee0ed41d/utils.py#L211
https://github.com/wangle53/3DCDNet/blob/4aaf38bbb9f7591ce1e3f32bcab38d21ee0ed41d/utils.py#L218

Do `lb0 `and `lb1 `in these two lines represent ground truth and `scores0 `and `scores1 `represent predicted values? @wangle53

**Comment by wangle53** [comment]
That's right.

**Comment by LinLin1031** [comment]
![image](https://github.com/wangle53/3DCDNet/assets/50825626/f9bb5e1f-ed84-4df7-89d7-a9b18246cdb5) 
Figure 1. Ground truth in the original dataset.
![image](https://github.com/wangle53/3DCDNet/assets/50825626/6fedd0d3-78e8-423e-97e0-d7bab8aa4af4) 
Figure 2.`Label` in the prediction result.

But why is it that for "39_1" in the test set, when I look at its ground truth, it looks like figure 1. But when I look at the `label `in the prediction result, it looks like figure 2. According to the answer above, the `label `in the prediction result is the gt, and both should be the same. What does the green colour that appears here represent? @wangle53

**Comment by wangle53** [comment]
Did you show two point clouds on the same page in fig2?

**Comment by LinLin1031** [comment]
![image](https://github.com/wangle53/3DCDNet/assets/50825626/b2a80c22-8745-4b97-b27a-5942cbf0c3c6)
No, it's a single file ([point2020_seg.txt](https://github.com/wangle53/3DCDNet/files/14064418/point2020_seg.txt)) obtained by testing.
When opening the file you can see that the column `label` has values of 0, 1 and 2, which is what I'm confused about. @wangle53

**Comment by wangle53** [comment]
In our experiments,before train and test phase, the ground points are pre-removed using a fixed threshold. For the convenience of visvalization, we recover the removed ground points after inference. However, the labels of the removed ground points are not processed while recover it. The fig2 shows a added object occurred in point cloud 2020, and a part of    the added object points with labels 1 was removed before train phase. When recover the whole point clouds after inference phase,the removed points with label 1 are directly stacked with the prediction results, this therefore leads to the case of shown in Figure 2.

**Comment by LinLin1031** [comment]
https://github.com/wangle53/3DCDNet/blob/4aaf38bbb9f7591ce1e3f32bcab38d21ee0ed41d/utils.py#L218
I get it. That is, the problem has no effect on the prediction results, only on the visualization of the results. And the problem arises because the line above multiplies `lb1` by 2, causing it to be different from the original label of the ground. I think this can be fixed by changing this line of code to `p1 = np.hstack((p1, lb1, scores1))`. Right? @wangle53

**Comment by wangle53** [comment]
You analysis is right, but your solution can't solve it. You can replace line 222 in utils.py with plane1 = np.hstack((plane1[:,:2], apl1,apl1))

**Comment by LinLin1031** [comment]
Sorry, I'm a little confused. Why do you need to get the XY coordinates of the ground? And repeat the label twice? @wangle53

**Comment by wangle53** [comment]
Correct it to [:,:3].

**Comment by LinLin1031** [comment]
My intuition is that `p1 = np.hstack((p1, lb1*2, scores1*2))` has changed the non-ground labels to 2, while the ground labels are still 1. This may still cause this problem. @wangle53

**Comment by wangle53** [comment]
If You want to avoid the case as shown in Fig2, You just need to replace line 222 in utils.py with plane1 = np.hstack((plane1[:,:3], apl1,apl1)). Another point need to be noticed is that, the removed ground points are not involved in training or test phase.

**Comment by LinLin1031** [comment]
Thanks for the advice, I've got the desired results. But I'm still trying to figure out why the multiplication by 2 in `p1 = np.hstack((p1, lb1*2, scores1*2))`? @wangle53

**Comment by wangle53** [comment]
This is simply to distinguish different categories. 0 denotes unchanged points, 1 and 2 denotes changed points. Specifically,1 denotes removed points, and 2 denotes added points.

---- Replied Message ----
| From | ***@***.***> |
| Date | 01/27/2024 07:56 |
| To | wangle53/3DCDNet ***@***.***> |
| Cc | wangzhixue王志学-西南交通大学 ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [wangle53/3DCDNet] A question about the SLPCCD dataset. (Issue #2) |

Thanks for the advice, I've got the desired results. But I'm still trying to figure out why the multiplication by 2 in p1 = np.hstack((p1, lb1*2, scores1*2))? @wangle53
