### ISSUE TITLE
How to visualize?

### ISSUE THREAD

**Issue by LinLin1031** [wangle53/3DCDNet#3]
Hello! 

I have successfully completed the test step and got the "test_prediction_PCs" folder. 

I would like to know how to visualize the results next, as shown in the paper? @wangle53

**Comment by wangle53** [comment]
Please use 'Cloudcompare' software. It is freely download online.

---- Replied Message ----
| From | ***@***.***> |
| Date | 01/23/2024 09:30 |
| To | wangle53/3DCDNet ***@***.***> |
| Cc | wangzhixue王志学-西南交通大学 ***@***.***>,
Mention ***@***.***> |
| Subject | [wangle53/3DCDNet] How to visualize? (Issue #3) |

Hello!

I have successfully completed the test step and got the "test_prediction_PCs" folder.

I would like to know how to visualize the results next, as shown in the paper? @wangle53
